apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    name: ubuntu-pod
spec:
  containers:
  - name: ubuntu-pod
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    command: ["sleep", "infinity"]
